"""Layer #1 (Provenance/Sentinel) ported to SCR. Real tests — the mapper runs
over a REAL exported SCR bundle (built here from a live mock team run), the
compliance_map tool is capability-gated, the enterprise package loads as a
two-team FOREST, and the sce.compliance team runs end to end with real native
tools and writes a real report. No fakes."""
import json
import os
import zipfile

import pytest
import yaml

from scr import compliance
from scr.capability import CapabilityManifest
from scr.evidence import export_team_bundle
from scr.gateway import MockAdapter, ModelResponse, ToolCall
from scr.sandbox import SandboxRunner
from scr.signer import sign_package
from scr.signing import Keystore, generate_keypair
from scr.state import Store
from scr.team import (TeamRunner, load_team_from_dir, load_team_from_package)
from scr.tools_native import build_native_tools

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PKG_SRC = os.path.join(ROOT, "packages", "selfconnect-enterprise")


_bundle_seq = [0]


def _make_real_bundle(tmp_path) -> str:
    """Run a small real mock team, export a sealed bundle, return its path.
    Each call uses a unique subdir so a test may build more than one."""
    _bundle_seq[0] += 1
    tmp_path = tmp_path / f"b{_bundle_seq[0]}"
    tmp_path.mkdir(parents=True, exist_ok=True)
    ad = tmp_path / "t" / "agents"; ad.mkdir(parents=True)
    for name, body in {
        "lead": {"capabilities": {"tools": ["fs_read"], "fs_read_roots": ["${WORKSPACE}"]},
                 "delegates": ["worker"]},
        "worker": {"capabilities": {"tools": ["fs_read"], "fs_read_roots": ["${WORKSPACE}"]}},
    }.items():
        body["name"] = name
        (ad / f"{name}.yaml").write_text(yaml.safe_dump(body))
    loaded = load_team_from_dir(str(tmp_path / "t"), str(tmp_path / "ws"))
    store = Store(str(tmp_path / "run.db"))
    adapters = {
        "lead": MockAdapter([ModelResponse("", (ToolCall("d", "delegate",
                            {"agent": "worker", "task": "look"}),)),
                            ModelResponse("done")]),
        "worker": MockAdapter([ModelResponse("finding: ok")]),
    }
    runner = TeamRunner(store, loaded, lambda a: adapters[a], lambda m: {},
                        provenance={"package": "selfconnect-enterprise",
                                    "version": "1.0.0", "key_id": "ktest",
                                    "content_sha256": "ab" * 32})
    res = runner.run("lead", "go")
    bundle = str(tmp_path / "run.scevidence")
    export_team_bundle(store, runner.last_team_id, b"k" * 32, bundle)
    store.conn.close()
    return bundle


# --------------------------------------------------------------- catalogs
def test_catalogs_loaded_verbatim():
    fws = compliance.load_frameworks()
    ids = {f["framework_id"] for f in fws}
    assert {"nist-800-53-r5-moderate", "iso-42001-2023",
            "eu-ai-act-2024", "nist-ai-rmf-1.0"} <= ids
    total = sum(len(f["controls"]) for f in fws)
    assert total == 45


# --------------------------------------------------------------- mapper
def test_map_real_bundle_satisfies_real_controls(tmp_path):
    res = compliance.map_bundle(_make_real_bundle(tmp_path))
    assert res["controls_total"] == 45
    # a real run's ledger evidences a meaningful, NON-trivial subset...
    assert 0 < res["controls_satisfied"] < 45          # not all, not none — honest
    # ...and specifically the ledger-integrity + provenance controls that SCR
    # genuinely produces should be satisfied somewhere.
    all_sigs = [s for f in res["frameworks"] for c in f["controls"]
                for s in c["signals"]]
    assert any(s["passed"] and "ledger events present" in s["detail"] for s in all_sigs)
    assert any(s["passed"] and "signed package governs" in s["detail"] for s in all_sigs)


def test_mapper_is_honest_about_unevidenced_signals(tmp_path):
    res = compliance.map_bundle(_make_real_bundle(tmp_path))
    sigs = {s["source"]: s for f in res["frameworks"] for c in f["controls"]
            for s in c["signals"]}
    # Sentinel-era sources SCR does not emit must be present AND failing, with a reason
    for src in ("monitors.drift_alerts", "red_team.runs", "transport.mTLS"):
        assert src in sigs and sigs[src]["passed"] is False
        assert "not evidenced" in sigs[src]["detail"].lower()
    # SHA-384 mismatch is reported truthfully, not hidden
    assert sigs["identity.hash_algorithm"]["passed"] is False
    assert "SHA-256" in sigs["identity.hash_algorithm"]["detail"]


def test_render_is_deterministic_and_marked(tmp_path):
    res = compliance.map_bundle(_make_real_bundle(tmp_path))
    md = compliance.render_markdown(res)
    assert "compliance mapping complete" in md
    assert "not the" in md and "model" in md          # the "generated by SCR" note
    # deterministic: re-render of the SAME result is byte-identical
    assert md == compliance.render_markdown(res)


# --------------------------------------------------------------- tool gating
def test_compliance_map_tool_capability_gated(tmp_path):
    ws = tmp_path / "ws"; ws.mkdir()
    out = tmp_path / "out"; out.mkdir()
    bundle = _make_real_bundle(tmp_path)                # OUTSIDE ws
    m = CapabilityManifest(tools=frozenset({"compliance_map"}),
                           fs_read_roots=(str(ws),), fs_write_roots=(str(out),))
    tools = build_native_tools(m, SandboxRunner())
    fn = tools["compliance_map"].fn
    # bundle outside the read root → denied, nothing written
    r = fn({"bundle": bundle, "out": str(out / "r.md")})
    assert "DENIED" in r and not (out / "r.md").exists()
    # move the bundle inside ws → satisfied
    inside = str(ws / "run.scevidence")
    os.replace(bundle, inside)
    r2 = fn({"bundle": inside, "out": str(out / "r.md")})
    assert "compliance mapping complete" in r2
    assert (out / "r.md").read_text(encoding="utf-8").startswith(
        "# SelfConnect Runtime — Compliance")
    # missing arg folds, never raises
    assert "bad_args" in fn({"bundle": inside})


# --------------------------------------------------------- multi-team package
def test_enterprise_package_is_a_two_team_forest():
    loaded = load_team_from_dir(PKG_SRC, "C:/ws", "C:/out")
    assert set(loaded.aliases) == {"sce.security-team", "sce.compliance"}
    assert loaded.team_of["lead"] == "lead"
    assert loaded.team_of["compliance"] == "compliance"
    # the two teams are disjoint trees
    assert loaded.team_for("auditor") is loaded.team_for("lead")
    assert loaded.team_for("compliance") is not loaded.team_for("lead")


def test_enterprise_package_builds_signs_and_verifies(tmp_path):
    from scr.loader import verify_package
    priv, pub = generate_keypair()
    out = str(tmp_path / "ent.scpkg")
    sign_package(PKG_SRC, out, "selfconnect-enterprise", "1.0.0", priv)
    ks = Keystore(); ks.add(pub)
    res = verify_package(out, ks)
    assert res.ok, res.error
    # both teams load from the SIGNED package
    lt = load_team_from_package(out, str(tmp_path / "ws"), str(tmp_path / "out"))
    assert lt.entry_for("sce.compliance") == "compliance"


# --------------------------------------------------- end-to-end compliance team
def test_sce_compliance_team_runs_end_to_end(tmp_path):
    """The REAL package team, real native tools, a real bundle in the workspace,
    a stand-in model that drives the exact tool calls the prompt specifies."""
    ws = tmp_path / "ws"; ws.mkdir()
    out = tmp_path / "out"; out.mkdir()
    # a real SCR bundle sits in the workspace to be mapped
    b = _make_real_bundle(tmp_path)
    bundle_in_ws = str(ws / "prior-run.scevidence")
    os.replace(b, bundle_in_ws)

    loaded = load_team_from_dir(PKG_SRC, str(ws), str(out))
    store = Store(":memory:")
    report_path = str(out / "compliance-report.md")

    class _Stand:
        def __init__(self): self.n = 0
        def complete(self, messages, tools):
            self.n += 1
            if self.n == 1:
                return ModelResponse("", (ToolCall("l", "fs_list", {"path": str(ws)}),))
            if self.n == 2:
                return ModelResponse("", (ToolCall("c", "compliance_map",
                    {"bundle": bundle_in_ws, "out": report_path}),))
            return ModelResponse("compliance mapping complete: controls mapped")

    sb = SandboxRunner(tmp_dir=str(tmp_path / "sbtmp"))
    runner = TeamRunner(store, loaded, lambda a: _Stand(),
                        lambda m: build_native_tools(m, sb), sandbox=sb)
    res = runner.run("sce.compliance", "map compliance for the prior run")
    assert res.stopped_reason == "completed"
    assert "compliance mapping complete" in res.final_text
    assert os.path.exists(report_path)
    body = open(report_path, encoding="utf-8").read()
    assert "Compliance Control Mapping" in body
    assert "controls satisfied by this run's ledger" in body
    # the ledger proves compliance_map actually executed
    ev = [json.loads(r["event"]) for r in store.conn.execute(
        "SELECT event FROM ledger WHERE session_id=? ORDER BY seq",
        (res.session_id,)).fetchall()]
    assert any(e.get("type") == "tool_exec" and e.get("tool") == "compliance_map"
               for e in ev)
